# Generated by Django 5.0.6 on 2026-03-21 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('raw_data', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawcustomer',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store'),
        ),
        migrations.AddField(
            model_name='rawinventorylevel',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store'),
        ),
        migrations.AddField(
            model_name='raworder',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store'),
        ),
        migrations.AddField(
            model_name='rawproduct',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store'),
        ),
        migrations.AddField(
            model_name='synclog',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='stores.store'),
        ),
        migrations.AddIndex(
            model_name='rawcustomer',
            index=models.Index(fields=['store', 'is_processed'], name='raw_custome_store_i_e93b13_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rawcustomer',
            unique_together={('store', 'shopify_id')},
        ),
        migrations.AddIndex(
            model_name='rawinventorylevel',
            index=models.Index(fields=['store', 'shopify_inventory_item_id'], name='raw_invento_store_i_2b6c4d_idx'),
        ),
        migrations.AddIndex(
            model_name='raworder',
            index=models.Index(fields=['store', 'is_processed'], name='raw_orders_store_i_b4b3ea_idx'),
        ),
        migrations.AddIndex(
            model_name='raworder',
            index=models.Index(fields=['received_at'], name='raw_orders_receive_3e23f6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='raworder',
            unique_together={('store', 'shopify_id')},
        ),
        migrations.AddIndex(
            model_name='rawproduct',
            index=models.Index(fields=['store', 'is_processed'], name='raw_product_store_i_43d8b0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rawproduct',
            unique_together={('store', 'shopify_id')},
        ),
    ]
