# Generated by Django 5.0.6 on 2026-03-21 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_customer_id', models.BigIntegerField(db_index=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('orders_count', models.IntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('accepts_marketing', models.BooleanField(default=False)),
                ('tags', models.TextField(blank=True)),
                ('rfm_segment', models.CharField(blank=True, db_index=True, max_length=50)),
                ('rfm_recency_score', models.IntegerField(blank=True, null=True)),
                ('rfm_frequency_score', models.IntegerField(blank=True, null=True)),
                ('rfm_monetary_score', models.IntegerField(blank=True, null=True)),
                ('last_order_date', models.DateTimeField(blank=True, null=True)),
                ('shopify_created_at', models.DateTimeField(blank=True, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wh_customers', to='stores.store')),
            ],
            options={
                'db_table': 'wh_customers',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_location_id', models.BigIntegerField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('address1', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='stores.store')),
            ],
            options={
                'db_table': 'wh_locations',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_order_id', models.BigIntegerField(db_index=True)),
                ('order_number', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('financial_status', models.CharField(blank=True, db_index=True, max_length=50)),
                ('fulfillment_status', models.CharField(blank=True, max_length=50)),
                ('subtotal_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_discounts', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('processed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('shopify_created_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='warehouse.customer')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.location')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wh_orders', to='stores.store')),
            ],
            options={
                'db_table': 'wh_orders',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_product_id', models.BigIntegerField(db_index=True)),
                ('title', models.CharField(max_length=500)),
                ('vendor', models.CharField(blank=True, max_length=255)),
                ('product_type', models.CharField(blank=True, db_index=True, max_length=255)),
                ('tags', models.TextField(blank=True)),
                ('status', models.CharField(db_index=True, default='active', max_length=50)),
                ('shopify_created_at', models.DateTimeField(blank=True, null=True)),
                ('shopify_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wh_products', to='stores.store')),
            ],
            options={
                'db_table': 'wh_products',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_variant_id', models.BigIntegerField(db_index=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('sku', models.CharField(blank=True, db_index=True, max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('inventory_quantity', models.IntegerField(default=0)),
                ('shopify_inventory_item_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='warehouse.product')),
            ],
            options={
                'db_table': 'wh_product_variants',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_line_item_id', models.BigIntegerField(db_index=True)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('variant_title', models.CharField(blank=True, max_length=255)),
                ('sku', models.CharField(blank=True, max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.productvariant')),
            ],
            options={
                'db_table': 'wh_order_items',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_quantity', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_levels', to='warehouse.location')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_levels', to='warehouse.productvariant')),
            ],
            options={
                'db_table': 'wh_inventory',
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['store', 'rfm_segment'], name='wh_customer_store_i_ffa664_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['last_order_date'], name='wh_customer_last_or_9306c0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('store', 'shopify_customer_id')},
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('store', 'shopify_location_id')},
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['store', 'financial_status'], name='wh_orders_store_i_ed3fcb_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['store', 'processed_at'], name='wh_orders_store_i_63e78d_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['processed_at'], name='wh_orders_process_b08747_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('store', 'shopify_order_id')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['store', 'status'], name='wh_products_store_i_be50ac_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_type'], name='wh_products_product_daa540_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('store', 'shopify_product_id')},
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'shopify_variant_id')},
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['product'], name='wh_order_it_product_077843_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['variant'], name='wh_order_it_variant_6fdb10_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'shopify_line_item_id')},
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['variant'], name='wh_inventor_variant_8e60d3_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['stock_quantity'], name='wh_inventor_stock_q_193278_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('variant', 'location')},
        ),
    ]
