# Generated by Django 5.0.6 on 2026-03-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryRevenueSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('period_start', models.DateField(db_index=True)),
                ('period_end', models.DateField()),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('revenue_pct', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'analytics_category_revenue',
            },
        ),
        migrations.CreateModel(
            name='DailyRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_profit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_orders', models.IntegerField(default=0)),
                ('avg_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'db_table': 'analytics_daily_revenue',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='InventoryMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_id', models.IntegerField(db_index=True)),
                ('product_title', models.CharField(max_length=500)),
                ('variant_title', models.CharField(blank=True, max_length=255)),
                ('sku', models.CharField(blank=True, max_length=255)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('avg_daily_sales', models.FloatField(default=0)),
                ('days_cover', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('critical', 'Critical'), ('low', 'Low'), ('ok', 'Healthy'), ('dead_stock', 'Dead Stock')], db_index=True, default='ok', max_length=20)),
                ('last_sold_days_ago', models.IntegerField(blank=True, null=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'analytics_inventory_metrics',
            },
        ),
        migrations.CreateModel(
            name='KPISnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue_30d', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('revenue_prev_30d', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('revenue_change_pct', models.FloatField(default=0)),
                ('profit_30d', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('profit_change_pct', models.FloatField(default=0)),
                ('orders_30d', models.IntegerField(default=0)),
                ('orders_change_pct', models.FloatField(default=0)),
                ('aov_30d', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('aov_change_pct', models.FloatField(default=0)),
                ('total_customers', models.IntegerField(default=0)),
                ('repeat_purchase_rate', models.FloatField(default=0)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'analytics_kpi_snapshot',
            },
        ),
        migrations.CreateModel(
            name='LocationRevenueSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=255)),
                ('period_start', models.DateField(db_index=True)),
                ('period_end', models.DateField()),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_orders', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'analytics_location_revenue',
            },
        ),
        migrations.CreateModel(
            name='ProductSalesSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(db_index=True)),
                ('period_end', models.DateField()),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_profit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('units_sold', models.IntegerField(default=0)),
                ('margin_pct', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'analytics_product_sales',
            },
        ),
        migrations.CreateModel(
            name='RFMScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recency', models.IntegerField(default=0)),
                ('frequency', models.IntegerField(default=0)),
                ('monetary', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('recency_score', models.IntegerField(default=1)),
                ('frequency_score', models.IntegerField(default=1)),
                ('monetary_score', models.IntegerField(default=1)),
                ('segment', models.CharField(blank=True, db_index=True, max_length=50)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'analytics_rfm_scores',
            },
        ),
    ]
