# Generated by Django 5.0.6 on 2026-03-21 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('stores', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryrevenuesummary',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store'),
        ),
        migrations.AddField(
            model_name='dailyrevenue',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_revenues', to='stores.store'),
        ),
        migrations.AddField(
            model_name='inventorymetric',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.product'),
        ),
        migrations.AddField(
            model_name='inventorymetric',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store'),
        ),
        migrations.AddField(
            model_name='kpisnapshot',
            name='store',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_snapshot', to='stores.store'),
        ),
        migrations.AddField(
            model_name='locationrevenuesummary',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store'),
        ),
        migrations.AddField(
            model_name='productsalessummary',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_summary', to='warehouse.product'),
        ),
        migrations.AddField(
            model_name='productsalessummary',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store'),
        ),
        migrations.AddField(
            model_name='rfmscore',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rfm_score', to='warehouse.customer'),
        ),
        migrations.AddField(
            model_name='rfmscore',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store'),
        ),
        migrations.AlterUniqueTogether(
            name='categoryrevenuesummary',
            unique_together={('store', 'category', 'period_start')},
        ),
        migrations.AddIndex(
            model_name='dailyrevenue',
            index=models.Index(fields=['store', 'date'], name='analytics_d_store_i_5e051b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyrevenue',
            unique_together={('store', 'date')},
        ),
        migrations.AddIndex(
            model_name='inventorymetric',
            index=models.Index(fields=['store', 'status'], name='analytics_i_store_i_278c05_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventorymetric',
            unique_together={('store', 'variant_id')},
        ),
        migrations.AlterUniqueTogether(
            name='locationrevenuesummary',
            unique_together={('store', 'location_name', 'period_start')},
        ),
        migrations.AddIndex(
            model_name='productsalessummary',
            index=models.Index(fields=['store', 'period_start'], name='analytics_p_store_i_956b72_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productsalessummary',
            unique_together={('store', 'product', 'period_start')},
        ),
        migrations.AddIndex(
            model_name='rfmscore',
            index=models.Index(fields=['store', 'segment'], name='analytics_r_store_i_90e65a_idx'),
        ),
    ]
