# Generated by Django 5.0.6 on 2026-03-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info'), ('success', 'Opportunity')], db_index=True, max_length=20)),
                ('category', models.CharField(choices=[('stockout', 'Stockout'), ('revenue', 'Revenue'), ('customer', 'Customer'), ('inventory', 'Inventory'), ('opportunity', 'Opportunity')], db_index=True, max_length=30)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('action_label', models.CharField(blank=True, max_length=100)),
                ('action_url', models.CharField(blank=True, max_length=255)),
                ('is_resolved', models.BooleanField(db_index=True, default=False)),
                ('dedup_key', models.CharField(blank=True, db_index=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'insights_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('revenue', 'Revenue'), ('product', 'Product'), ('customer', 'Customer'), ('inventory', 'Inventory'), ('opportunity', 'Opportunity')], max_length=30)),
                ('severity', models.CharField(default='info', max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('action', models.CharField(blank=True, max_length=255)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'insights_insights',
                'ordering': ['-created_at'],
            },
        ),
    ]
