# Generated by Django 5.0.6 on 2026-03-21 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insights', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='stores.store'),
        ),
        migrations.AddField(
            model_name='insight',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='stores.store'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['store', 'severity', 'is_resolved'], name='insights_al_store_i_0b0d46_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['store', 'is_resolved'], name='insights_al_store_i_938b1b_idx'),
        ),
    ]
