# Generated by Django 5.0.6 on 2026-03-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_domain', models.CharField(db_index=True, max_length=255, unique=True)),
                ('shop_name', models.CharField(blank=True, max_length=255)),
                ('access_token', models.CharField(max_length=512)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('timezone', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('shopify_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Store',
                'db_table': 'stores',
            },
        ),
    ]
