# Generated by Django 5.0.6 on 2026-05-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='shopify_auth',
            field=models.BooleanField(default=False),
        ),
    ]
